import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Input from '@/components/input';
import { NuqsAdapter } from 'nuqs/adapters/next';
import Link from 'next/link';
import { Suspense } from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="bg-red-300 text-center">
            <h1 className="text-4xl">This is rendered in root layout</h1>
            <div>
              <Link href="/">Go to Homepage</Link>
              <Link href="/subpage">Go to Subpage</Link>
            </div>
            <Suspense>
              <Input />
            </Suspense>
          </div>
          {children}
        </body>
      </html>
    </NuqsAdapter>
  );
}
